apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: app
data:
  DBHOST: 
  DBNAME: 
  DBPASSWORD: 
  DBPORT: 
  DBUSER: 
  JWT_KEYS: 
  REDIS_HOST: 
  REDIS_PASS: 
  REDIS_PORT: 
  VUE_APP_URL: 
