version: "3.7"
services: 
  redis:
    restart: always
    container_name: redis
    image: redis:alpine3.16
    command: redis-server
    environment: 
      - REDIS_PASSWORD='${REDIS_PASS}'
    ports:  
      - "6379:6379"
    volumes: 
      - ./redis-data:/data

  postgres:
    restart: always
    container_name: postgres
    image: postgres:alpine3.16
    environment:
      - POSTGRES_USER='${DBUSER}'
      - POSTGRES_PASSWORD='${DBPASSWORD}'
      - POSTGRES_DB='{DBNAME}'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  postgres:
  redis-data: