- hosts: localhost
  connection: local

  vars:
    project: be
    namespace: app-backend
    src: /home/mrizkiprmn/github/app-backend/Charts/backend

  pre_tasks:

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes

    - name: install Helm Diff
      kubernetes.core.helm_plugin:
        state: present
        plugin_path: https://github.com/databus23/helm-diff
  
  tasks:

    - name: helm deploy
      kubernetes.core.helm:
        release_state: present
        name: "{{ project }}"
        namespace: "{{ namespace }}"
        chart_ref: "{{ src }}"
